### ISSUE TITLE
Version detection

### ISSUE THREAD

**Issue by SekoRulez** [GaretJax/phpbrowscap#17]
The version detection seems the off in some cases. I download the new 1.0 version.

Mozilla/5.0 (compatible; Yahoo! Slurp/3.0; http://help.yahoo.com/help/us/ysearch/slurp)

This useragent is detected als Yahoo! Slurp 0. While is should be Yahoo! Slurp 3.0
as it is on Gary Keiths website

http://browsers.garykeith.com/tools/ua-search.asp

Perhaps there are other situations in which this goes wrong. I just happen to come accross this example.

**Comment by quentin389** [comment]
Closing. The user agent in question is being detected correctly.
