### ISSUE TITLE
New version of browscap.ini.

### ISSUE THREAD

**Issue by ghost** [GaretJax/phpbrowscap#18]
We will be releasing a new  format of browscap.ini on Monday. We've maintained backward compatibility and don't anticipate any issues, but someone really needs to test it with phpbrowscap to be sure. Thanks. ~gary.

**Comment by Krinkle** [comment]
I just ran a test with version 5000 on GaretJax/phpbrowscap (by locally replacing `browscap.ini` and removing the cache file) and I got a screen full of this:

```
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
Notice: Undefined index: deviceName in /Users/krinkle/Development/github/jquery/testswarm/inc/libs/GaretJax-phpbrowscap/browscap/Browscap.php on line 369
```

Considering that `Browscap.php` does not reference `deviceName` itself, I think this is an issue with the source file itself. Browscap.php uses the `DefaultProperties` one as base. And `browscap.ini` has an inconsistency (some use `Device_Name`, others use `deviceName`).

Manually adding `deviceName=unknown` to `[DefaultProperties]` in `browscap.ini` fixed it.

I've reported it upstream at GaryKeith/browscap#4.

**Comment by ghost** [comment]
Thanks for taking the time to test it. It's been fixed along with several other changes you submitted that got committed.
