### ISSUE TITLE
unrecognized UA string

### ISSUE THREAD

**Issue by toneplex** [GaretJax/phpbrowscap#2]
The following UA 

Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.04 (lucid) Firefox/3.6.13  

is being recognized as
Windows Firefox 3.6

**Comment by GaretJax** [comment]
Please report unrecognized user agents directly to Gary Keith: http://browsers.garykeith.com/

The browscap class is only responsible to parse its file.

**Comment by toneplex** [comment]
I used the User Agent Checker (http://browsers.garykeith.com/tools/agent-checker.asp) on his site to test the string before submitting it, and it is recognized correctly.  So what is the next step then?

**Comment by GaretJax** [comment]
Probably to empty you cache.

This is the result I obtain with the latest version:

```
stdClass Object
(
    [browser_name] => Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.2.13) Gecko/20101206 Ubuntu/10.04 (lucid) Firefox/3.6.13
    [browser_name_regex] => ^mozilla/5\.0 \(x11; .*; .*linux.*; .*; rv\:1\.9\.2.*\) gecko/.* firefox/3\.6.*$
    [browser_name_pattern] => Mozilla/5.0 (X11; *; *Linux*; *; rv:1.9.2*) Gecko/* Firefox/3.6*
    [Parent] => Firefox 3.6
    [Platform] => Linux
    [Browser] => Firefox
    [Version] => 3.6
    [MajorVer] => 3
    [MinorVer] => 6
    [Frames] => 1
    [IFrames] => 1
    [Tables] => 1
    [Cookies] => 1
    [JavaApplets] => 1
    [JavaScript] => 1
    [CssVersion] => 3
    [supportsCSS] => 1
    [Alpha] => 
    [Beta] => 
    [Win16] => 
    [Win32] => 
    [Win64] => 
    [BackgroundSounds] => 
    [CDF] => 
    [VBScript] => 
    [ActiveXControls] => 
    [isBanned] => 
    [isMobileDevice] => 
    [isSyndicationReader] => 
    [Crawler] => 
    [AOL] => 
    [aolVersion] => 0
)
```

**Comment by GaretJax** [comment]
Uhm... Just noticed that my version was from April 10, 2010 (still works with the latest version, though).

Which version are you using? The lite one?

**Comment by toneplex** [comment]
My apologies, it was my fault. I had overridden the platform while testing and didn't see that yesterday.
