### ISSUE TITLE
PHP 5 Compatibility - 5.3 not 5.x

### ISSUE THREAD

**Issue by radmoose** [GaretJax/phpbrowscap#21]
The README.markdown mentions that this is PHP 5 compatible.

As the code uses a namespace, it is 5.3.x+ compatible.

Has anyone made a modified version that is PHP 5 (or at least 5.2) compatible?

**Comment by GaretJax** [comment]
radmoose, you can find it a couple of commits behind, namely: https://github.com/GaretJax/phpbrowscap/tree/8dd776a529941b1bd3c8554f6056f9454206b1c8

**Comment by GaretJax** [comment]
Fixed in 5d98900
