### ISSUE TITLE
Not available in Composer?

### ISSUE THREAD

**Issue by Synchro** [GaretJax/phpbrowscap#23]
I'm following the suggestion to [use composer](https://github.com/GaretJax/phpbrowscap/wiki/QuickStart) in the quickstart, but it doesn't appear to work. My `composer.json` file contains:

```
{
    "require": {
        "GaretJax/phpbrowscap": "*"
    }
}
```

but running composer doesn't find it:

```
Loading composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package garetjax/phpbrowscap * could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I see that in packagist it's tagged as `dev-master` - does that not match `*`? Is it the docs, the code or the package that's wrong? Either way, something needs fixing!

**Comment by jonathaningram** [comment]
Does it work if you change the `*` to `dev-master`? I can't remember if Composer requires correct casing on the packages, but also try the lowercase version: `garetjax/phpbrowscap` in your composer.json.

**Comment by Synchro** [comment]
It did work just by changing \* to dev-master. This suggests that \* isn't some kind of wildcard after all? Composer seems to do the lowercasing by itself (you can see that in the error message).
