### ISSUE TITLE
Browscap Project has Closed

### ISSUE THREAD

**Issue by JoshuaEstes** [GaretJax/phpbrowscap#24]
The automatic updates are breaking. The cause for this is that the project is closed, however there are a few people that are trying to get it back up and going. Just thought I would let you know.

**Comment by Ultrabenosaurus** [comment]
For those interested, the negotiations for transferring ownership of the project are taking place here:
https://groups.google.com/forum/#!topic/browscap/pk_dkkqdXzg

**Comment by JoshuaEstes** [comment]
Thanks, I got the organization, Rad Moose seems to be taking the lead on this. I'll continue monitoring this. Do you know if he has a GH account?

**Comment by Ultrabenosaurus** [comment]
I don't, sorry. I only picked up on the Group when the project I'm using PHPBrowscap in started giving me entire pages of errors a few hours ago.

I heard last week that the project was going down, but didn't know it was going to happen this soon so I've not been following the discussions very closely.

**Comment by JoshuaEstes** [comment]
This completely blindsided me. Had no idea this was gonna happen, been searching online for a little bit now trying to find some type of archive. I think he should have at lease left the github code up so there could be something that I could work with =\

**Comment by Ultrabenosaurus** [comment]
I know what you mean. Luckily I downloaded a copy on October 12th for my project so users have a fallback in case they can't use PHPBrowscap's auto-update feature, so technically I'm okay. I want to say its annoying, but he was basically doing it all himself and getting next to nothing in return for over a decade, so I can understand why he wants to move on.

**Comment by radmoose** [comment]
Why yes, I do have a GH account. =)

This transition blindsided me as well.  I am working as fast as I can to get URLs back online for the Browser Capabilities Project.

For those who have a working download, you can go to about line 109 and find the following code....

```
public $doAutoUpdate = true;
```

Change that to FALSE for now and it will stop trying to connect for updates.

I will post the updated (possibly temporary) URLs as soon as they are online and tested.

The next step after getting a temporary site back online is to work on getting the whole project back online.

**Comment by radmoose** [comment]
Thanks to the assistance of Joshua Estes for providing additional testing, the parts that are often used for automatic update scripts are in place.

The following URL replaces the Update URL
Revised: http://tempdownloads.browserscap.com/stream.php?BrowsCapINI
Original: http://browsers.garykeith.com/stream.asp?BrowsCapINI

The following URL replaces the Version Date check URL 
Revised: http://tempdownloads.browserscap.com/versions/version-date.php
Original: http://browsers.garykeith.com/versions/version-date.asp

In phpbrowscap libary, around line 100 or so in Browscap.php the two URLs that match above should be replaced with the revised URLs.

Do note that these URLs are temporary as to keep sites functioning.  I will be monitoring the temporary site and adjust as needed.

There is a temporary web page at http://tempdownloads.browserscap.com/ for other downloads.  Please use the alternate links whenever possible.

The site is setup to also redirect .asp pages to the .php pages just in case.

UPDATE: Fixed a typo in the Original URL for the Update URL. Should not have affected anything other than probably if you used it to search the code, you wouldn't find an exact match.  Also, some test code snuck in the temporary Basic Download links and the file served was the php_browscap.ini file and not the selected file. This has now been corrected. The proper file is transferred.

**Comment by Ultrabenosaurus** [comment]
Thanks radmoose! Works perfectly :smile:

**Comment by lecajer** [comment]
![image](https://f.cloud.github.com/assets/2142505/190617/1883bc08-7f00-11e2-8409-9155aa0e9fdc.png)

**Comment by radmoose** [comment]
Corrected.

**Comment by lecajer** [comment]
:+1:

**Comment by jdlx** [comment]
Any updates on the BROWSCAP project migration?

**Comment by quentin389** [comment]
All the URLs are corrected now in the phpbrowscap class.

Closing the issue.
