### ISSUE TITLE
getBrowser() takes 0.0349s to process a single User Agent string

### ISSUE THREAD

**Issue by rdev5** [GaretJax/phpbrowscap#26]
<?php
$ua = 'Mozilla/5.0 (iPad; U; CPU OS 4_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko)';

$t = microtime(true);
$browser = $b->getBrowser($value);
echo 'Took '.(microtime(true)-$t).'s';
exit;
?>

getBrowser() takes 0.0349s to process a single User Agent string and appears to be dependent on the cache file, which for some reason, seems to keep getting reset (!$this->_cacheLoaded).

**Comment by quentin389** [comment]
Performance has been improved. Parsing + including the classes is now between 3 and 11 times faster. See [changelog](https://github.com/GaretJax/phpbrowscap/blob/master/CHANGELOG.md) for details.

The cache getting reset is probably a problem on your side. Do you still experience this issue?

**Comment by quentin389** [comment]
No answer. I assume it's fixed.
