### ISSUE TITLE
cell phone not identified

### ISSUE THREAD

**Issue by tstefan** [GaretJax/phpbrowscap#3]
I have the latest Browscap.php fine and it works with firefox 6 
when using  my T-Mobile G2 phone ts not identifying the browser or flagging it as mobile,
output from $bc->getBrowser() below

thanks 

stdClass Object ( 
  [browser_name] => Mozilla/5.0 (Linux; U; Android 2.2; en-us; T-Mobile G2 Build/FRF91) AppleWebKit/533.1(KHTML, like Gecko) Version/4.0 Mobile Safari/533.1
  [browser_name_regex] => ^.*$ 
  [browser_name_pattern] => \* 
  [Browser] => Default Browser 
  [Version] => 0 
  [MajorVer] => 0 
  [MinorVer] => 0 
  [Platform] => unknown 
  [Alpha] => 
  [Beta] => 
  [Win16] => 
  [Win32] => 
  [Win64] => 
  [Frames] => 
  [IFrames] => 
  [Tables] => 
  [Cookies] => 
  [BackgroundSounds] => 
  [JavaScript] => 
  [VBScript] => 
  [JavaApplets] => 
  [ActiveXControls] => 
  [isBanned] => 
  [isMobileDevice] => 
  [isSyndicationReader] => 
  [Crawler] => 
  [CssVersion] => 0 
  [AolVersion] => 0
)

**Comment by GaretJax** [comment]
Please report undetected browsers directly to http://browsers.garykeith.com/, I'm not responsible for the database maintenance!
