### ISSUE TITLE
INI files headers are treated as a match pattern even if they are not ("WebTV" should not match anything)

### ISSUE THREAD

**Issue by quentin389** [GaretJax/phpbrowscap#33]
It's a problem with the ini files construction. See the bug report at https://github.com/browscap/browscap/issues/3

**Comment by quentin389** [comment]
This is also an enhancement, because it overrides the default `get_browser()` behavior.

**Comment by quentin389** [comment]
Fixed.

**Comment by anna64000** [comment]
thanks
