### ISSUE TITLE
Acer Iconia Tab A500 Reports as Non-Mobile

### ISSUE THREAD

**Issue by TheFoot** [GaretJax/phpbrowscap#5]
This tablet shows the following output from getBrowser():

stdClass Object (
[browser_name] => Mozilla/5.0 (Linux; U; Android 3.2; en-us; A500 Build/HTJ85B) AppleWebKit/534.13 (KHTML, like Gecko) Version/4.0 Safari/534.13 
[browser_name_regex] => ^mozilla/5.0 (._linux._) applewebkit/.\* (khtml, like gecko) ._version/4.._ safari/._$ 
[browser_name_pattern] => Mozilla/5.0 (_Linux_) AppleWebKit/_ (KHTML, like Gecko) _Version/4._ Safari/*
 [Parent] => Safari 4.0 
[Platform] => Linux
 [Browser] => Safari 
[Version] => 4.0
 [MajorVer] => 4
 [Win32] => 1 
[Frames] => 1 
[IFrames] => 1
 [Tables] => 1 
[Cookies] => 1
 [JavaScript] => 1
 [JavaApplets] => 1
 [CssVersion] => 3
 [MinorVer] => 0
 [Alpha] =>
 [Beta] =>
 [Win16] => 
[Win64] =>
 [BackgroundSounds] => 
[VBScript] =>
 [ActiveXControls] => 
[isBanned] =>
 [isMobileDevice] =>
 [isSyndicationReader] =>
 [Crawler] =>
 [AolVersion] => 0 )

**Comment by GaretJax** [comment]
Phpbrowscap is only a class which READS the browscap.ini file provided by Gary Keith. Please refer to him for issues regarding wrong data.
