### ISSUE TITLE
At Mac OS X 10.9.4 gets only 10.9

### ISSUE THREAD

**Issue by vojtasvoboda** [GaretJax/phpbrowscap#69]
At Mac OS X version 10.9.4 prints only 10.9. and should print 10.9.4. See http://bit.ly/1wLQClq

**Comment by mimmi20** [comment]
Thats right. We dont detect the Micro Version.

**Comment by vojtasvoboda** [comment]
So, its bug or feature? :-) If I should look for another library, or it will be fixed or pull request need to be created?

**Comment by mimmi20** [comment]
If you really need the Micro Version, you should look for another library.

**Comment by vojtasvoboda** [comment]
Ok thanks.
