### ISSUE TITLE
Update URL is a redirect and causes date errors

### ISSUE THREAD

**Issue by xoob** [GaretJax/phpbrowscap#7]
The update URL has changed to `http://browsers.garykeith.com/versions/version-date.asp` and should be updated in the code.

While the old one returns a 304 Moved header, that redirect is not always followed and an attempt to parse the redirection HTML below leads to `strtotime()` failing and ultimately an exception.

```
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://browsers.garykeith.com/versions/version-date.asp">here</a></body>
```

**Comment by GaretJax** [comment]
Thanks for the report. The URL is updated in the source. Package distribution follows.
